services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      AUTH_TOKEN: test
      DB_SQLITE_ENABLED: true
      DB_SQLITE_FILE_PATH: /data/sqlite.db
    volumes:
      - data:/data
    ports:
      - "4000:4000"
