name: Build and Publish Nightly

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - ".vscode/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: api
          tags: nightly,${{ github.sha }}
          registry: ghcr.io
          directory: ./
          dockerfile: ./Dockerfile
          addLatest: false
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
